services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile_cv
    command: sh -c "cd API && uvicorn cv:app --reload --host 0.0.0.0 --port 8080"
    ports: 
      - 8080:8080
    volumes: 
      - ./API/cv.py:/app/API/cv.py

