services:
  web:
    build: 
      context: .
      dockerfile: dockerfile-yolo 
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8090"
    ports: 
      - "8090:8090"
    volumes: 
      - ./main.py/:/app/main.py  
    environment:
      - PYTHONUNBUFFERED=1 